# Generated by Django 5.1.1 on 2024-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('CEO', 'CEO'), ('Team Lead', 'Team Lead')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
